[projects."github.com/dklawren/bmo"]
approved-commands = [
    "cp -pr {{ primary_worktree_path }}/{CLAUDE.md,.code-review-graph} {{ worktree_path }}/ && code-review-graph update",
]

[projects."github.com/mozilla-conduit/phabricator-etl"]
approved-commands = [
    "cp -pr {{ primary_worktree_path }}/{CLAUDE.md,.code-review-graph} {{ worktree_path }}/ && code-review-graph update",
]
