#!/usr/bin/env bash

LOGOUT="󰍃  Logout"
SUSPEND="󰒲  Suspend"
REBOOT="󰜉  Restart"
SHUTDOWN="󰐥  Shutdown"

CHOSEN=$(printf "%s\n" "$LOGOUT" "$SUSPEND" "$REBOOT" "$SHUTDOWN" \
    | fuzzel --config "$HOME/.config/fuzzel/fuzzel.ini" --dmenu --prompt "  Power ")

case "$CHOSEN" in
    "$LOGOUT")   swaymsg exit ;;
    "$SUSPEND")  systemctl suspend ;;
    "$REBOOT")   systemctl reboot ;;
    "$SHUTDOWN") systemctl poweroff ;;
esac
