theme = "dark_plus"

[editor]
true-color = true
cursorline = true
color-modes = true
auto-save = true
bufferline = "always"
shell = ["zsh", "-c"]
idle-timeout = 5

[editor.statusline]
left = ["version-control", "mode", "spinner", "file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
esc = ["collapse_selection", "keep_primary_selection"]
p = "paste_clipboard_after"
P = "paste_clipboard_before"
y = "yank_joined_to_clipboard"
D = ["yank_main_selection_to_clipboard", "delete_selection"]
V = "extend_to_line_end"
C-k = ":buffer-next"
C-j = ":buffer-previous"
C-b = ":buffer-close"
# C-f = [":new", ":insert-output lf-pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme sonokai"]
# C-f = [":new", ":insert-output lf-pick", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true
display-signature-help-docs = true
display-inlay-hints = true
goto-reference-include-declaration = true
snippets = true

[editor.indent-guides]
render = true
