[window]
dynamic_padding = true
padding.x = 5
padding.y = 5
opacity = 0.97
decorations = "none"

[env]
TERM = "xterm-256color"

[scrolling]
history = 10000
multiplier = 3

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[font]
size = 12
offset.x=0
offset.y=-3

glyph_offset.x=0
glyph_offset.y=-1

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"
[font.bold]
family = "FiraCode Nerd Font"
style = "ExtraBold"
[font.italic]
family = "FiraCode Nerd Font"
style = "SemiBold Italic"
[font.bold_italic]
family = "FiraCode Nerd Font"
style = "ExtraBold Italic"
