# title bar
font pango:"Cascadia Code NF" Regular 12
titlebar_padding 1
titlebar_border_thickness 0

# adjusting borders
for_window [app_id="^.*"] border pixel 2
default_border none
default_floating_border none
for_window [class=".*"] title_format "*%title"

# Hide borders at the edge of the screen
hide_edge_borders smart

###############
# Gaps settings
###############
gaps inner 5
gaps outer 1
gaps top 1
gaps bottom 1

# Hide gaps when there is only 1 window
smart_gaps on

######################################
# color settings fo windows
######################################

# Catppuccin Mocha Color Scheme
# https://github.com/catppuccin/catppuccin
set $bg-color      #1e1e2e
set $bg-alt        #181825
set $bg-highlight  #313244
set $fg-color      #cdd6f4
set $fg-dark       #bac2de
set $comment       #6c7086

set $blue          #89b4fa
set $cyan          #89dceb
set $green         #a6e3a1
set $red           #f38ba8
set $yellow        #f9e2af
set $orange        #fab387
set $purple        #cba6f7
set $lavender      #b4befe

# Property Name          Border        BG             Text        Indicator   Child Border
client.focused           $blue         $bg-highlight  $fg-color   $lavender   $blue
client.focused_inactive  $comment      $bg-alt        $fg-dark    $bg-color   $comment
client.unfocused         $bg-highlight $bg-color      $comment    $bg-color   $bg-highlight
client.urgent            $red          $red           $bg-color   $red        $red
client.placeholder       $bg-color     $bg-color      $fg-dark    $bg-color   $bg-color
client.background        $bg-color
