# default i3 tiling mode:
workspace_layout default
focus_follows_mouse no
focus_wrapping no

##########################################
# configuration for workspace behaviour: #
##########################################
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"

################################
#     Assigned Workspace       #
################################

# (W-1)
# ========== Email Clients ==========
assign [class="(?i).*thunderbird.*"] $ws1

# (W-2)
# ========== Communication ==========
assign [app_id="(?i).*telegram.*"] $ws2
assign [class="(?i).*discord.*"] $ws2
assign [class="(?i).*slack.*"] $ws2
assign [app_id="(?i).*element.*"] $ws2
assign [app_id="(?i).*fractal.*"] $ws2

# (W-3)
# ========== Browser ===========
assign [app_id="(?i).*firefox.*"] $ws3
assign [app_id="(?i).*brave.*"] $ws3
assign [class="(?i).*brave.*"] $ws3
assign [app_id="(?i).*librewolf.*"] $ws3
assign [app_id="(?i).*zen.*"] $ws3

# (W-4)
# ========== Terminals ==========
assign [app_id="(?i).*alacritty.*"] $ws4
assign [app_id="(?i).*wezterm.*"] $ws4
assign [app_id="(?i).*ghostty.*"] $ws4
assign [app_id="(?i).*kitty.*"] $ws4
assign [app_id="(?i).*foot.*"] $ws4

# (W-5)
# ========== Media ===========
assign [class="(?i).*spotify.*"] $ws5
assign [app_id="(?i).*pulp.*"] $ws5
assign [app_id="(?i).*tuba.*"] $ws5
assign [app_id="(?i).*zoom.*"] $ws5

# (W-6)
# ========== Office Suits and tools ===========
assign [app_id="(?i).*office.*"] $ws6
assign [app_id="(?i).*zathura.*"] $ws6
assign [class="(?i).*onlyoffice.*"] $ws6

# (W-7)
# ========== Settings and Misc. ===========
assign [app_id="(?i).*gnome-disks.*"] $ws7
assign [app_id="(?i).*blueman-manager.*"] $ws7
assign [app_id="(?i).*obsproject.*"] $ws7
assign [app_id="(?i).*pavucontrol.*"] $ws7
assign [app_id="(?i).*nwg-look.*"] $ws7
