theme = "sonokai"

[editor]
true-color = true
cursorline = true
color-modes = true
auto-save = true
bufferline = "always"
shell = ["zsh", "-c"]
rulers = [80]

[editor.statusline]
left = ["version-control", "mode", "spinner", "file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
 
[editor.lsp]
display-messages = true
display-signature-help-docs = true
display-inlay-hints = true
snippets = true

[editor.indent-guides]
render = true