[[language]]
name = "perl"
language-server = { command = "perlnavigator", args = ["--stdio"] }
formatter = { command = "perltidy", args = ["-st"] }
file-types = ["perl", "pm", "pl", "cgi", "t"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
scope = "source.perl"
shebangs = ["perl"]
roots = []

[language.config.perlnavigator]
perlcriticProfile = "/var/home/dkl/devel/github/mozilla/bmo-new/upstream/master/.perlcriticrc"
perltidyProfile = "/var/home/dkl/devel/github/mozilla/bmo-new/upstream/master/.perltidyrc"
enableWarnings = "true"
includePaths = ["./", "./lib", "~/perl5/lib/perl5"]
includeLib = true
enableProgress = true
perlcriticEnabled = true
perltidyEnabled = true

[grammar]
name = "perl"
source = { git = "https://github.com/ganezdragon/tree-sitter-perl" }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
