[[language]]
name = "perl"
scope = "source.perl"
file-types = ["perl", "pm", "pl", "cgi", "t"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
shebangs = ["perl"]
language-servers = [ "perlnavigator" ]
formatter = { command = "perltidy", args = ["-st"] }
roots = [".perlcriticrc"]

[language-server.perlnavigator]
command = "perlnavigator"
args = ["--stdio"]

[language-server.perlnavigator.config]
includePaths = ['/var/home/dkl/.perlbrew/libs/perl-5.38.0@dkl/lib/perl5', './', './lib']
perlcriticProfile = '/var/home/dkl/devel/github/mozilla/bmo/upstream/master/.perlcriticrc'
perltidyProfile = '/var/home/dkl/devel/github/mozilla/bmo/upstream/master/.perltidyrc'
perlPath = 'perl'
enableWarnings = true
perlcriticEnabled = true
perltidyEnabled = true

[[language]]
name = "html"
file-types = ["html", "tmpl"]

[[grammar]]
name = "perl"
source = { git = "https://github.com/ganezdragon/tree-sitter-perl" }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
